### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Jeffrey-van-Ham**
- update selectors
- use ticketswap translations
- add colors

### CODE REVIEW

**Comment by needlzzz** [comment]
I tried your last commit and i get the following errors (not really useful lol): 

10:29:59 - Exception: TypeError: Cannot read properties of undefined (reading 'undefined')
10:30:02 - Exception: TypeError: Cannot read properties of undefined (reading 'undefined')

**Comment by RasmusBacklund** [comment]
Even with @Jeffrey-van-Ham's code corrected, the program returns invalid URL. Is this fixable? I think it has to do with availableListings never getting any values.

**Comment by Jeffrey-van-Ham** [comment]
@RasmusBacklund ticketswap changed their codebase again. I do have a workaround which does seem to work. They do block you quite often for a couple of hours if you're running the code for a while. I could put it online if you want.

**Comment by RasmusBacklund** [comment]
That would be very nice!

**Comment by Jeffrey-van-Ham** [comment]
Should be updated. Let me know if it works

**Comment by RasmusBacklund** [comment]
Does not work, maybe you could enable the issue section on your fork (if that is possible) so we don't have to discuss here. Line 45 ` const url = HOST + listing.uri.path;` is the issue. @Jeffrey-van-Ham

**Comment by Jeffrey-van-Ham** [comment]
Its open now

**Pull request closed without merging**
